### ISSUE TITLE
无法安装GrowingIO

### ISSUE THREAD

**Issue by sicaboy** [growingio/growingio-pods#2]
执行pod install时 出现如下错误。
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
pod 'GrowingIO'
```

```
Installing GrowingIO (0.9.41)

[!] Error installing GrowingIO
[!] /usr/bin/curl -f -L -o /var/folders/pk/w4wh8y2d11s86tczb7pzc2zm0000gn/T/d20170402-8925-1wto0j9/file.zip http://growing.ufile.ucloud.cn/sdk/GrowingIO-iOS-SDK-0.9.41-20161104164507.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

貌似是文件没有找到

**Comment by CastleChe** [comment]
因为历史版本会有问题，所以我们只会在服务器保留最新版本，我们也希望客户始终安装最新版本。

在安装 pod 时，请确保不要使用 --no-repo-update 选项，或者先用 pod repo update 来更新一下本地的所有 repo 信息，然后再安装。

安装前您可以执行命令 “pod spec cat GrowingIO” 看一下，从这个命令的输出里可以看到，我们当前的版本号是 0.9.47，下载地址是 http://growing.ufile.ucloud.com.cn/sdk/GrowingIO-iOS-SDK-0.9.47-20170111143620.zip ，下载的 SHA1 值是 52d0c4c1aebe311d63c2de8dcac3f9cf5e87d09e，您可以对照着看一下。

此外，当您集成时遇到任何问题（包括 pod 的问题）时，为了能更及时地帮到您，建议您在我们的网站 www.growingio.com 上登陆您的账号，然后点击右上角的“提交问题”来联系我们，我们会及时解决您的问题。

**Comment by HaoChe** [comment]
因为历史版本会有问题，所以我们只会在服务器保留最新版本，我们也希望客户始终安装最新版本。

在安装 pod 时，请确保不要使用 --no-repo-update 选项，或者先用 pod repo update 来更新一下本地的所有 repo 信息，然后再安装。

安装前您可以执行命令 “pod spec cat GrowingIO” 看一下，从这个命令的输出里可以看到，我们当前的版本号是 0.9.47，下载地址是 http://growing.ufile.ucloud.com.cn/sdk/GrowingIO-iOS-SDK-0.9.47-20170111143620.zip ，下载的 SHA1 值是 52d0c4c1aebe311d63c2de8dcac3f9cf5e87d09e，您可以对照着看一下。

此外，当您集成时遇到任何问题（包括 pod 的问题）时，为了能更及时地帮到您，建议您在我们的网站 www.growingio.com 上登陆您的账号，然后点击右上角的“提交问题”来联系我们，我们会及时解决您的问题。

**Comment by HaoChe** [comment]
暂时没有更多回复，所以先关闭这个 issue。如果仍有疑问，可以开启新的 issue，或者重新开启这个 issue。同时我们欢迎您登陆我们的网站，通过点击右上角的“提交问题”来联系我们。
