### ISSUE TITLE
导致MBProgressHUD显示异常

### ISSUE THREAD

**Issue by ticsmatic** [growingio/growingio-pods#4]
iOS端刚刚引入growingio的Pod，运行就发现导致项目中的MBProgressHUD显示异常，其它问题不知道还有没有

**Comment by ticsmatic** [comment]
#3 里面已经提到解决，我现在是1.1.0版本，仍未解决，还得自己处理

**Comment by sishen** [comment]
@west-east 感谢使用 GrowingIO. 下个版本的发布里面会包含这个问题的修复，目前我们在内部测试中。
